//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        public Artikli()
        {
            this.Stavke_narudzbe_racuna = new HashSet<Stavke_narudzbe_racuna>();
        }
    
        public int ID_artikal { get; set; }
        public Nullable<int> ID_artikal_podkategorija { get; set; }
        public string Naziv { get; set; }
        public Nullable<double> Bodovi { get; set; }
        public Nullable<double> Cijena { get; set; }
        public Nullable<int> ID_mjerna_jedinica { get; set; }
    
        public virtual Artikli_podkategorija Artikli_podkategorija { get; set; }
        public virtual Mjerne_jedinice Mjerne_jedinice { get; set; }
        public virtual ICollection<Stavke_narudzbe_racuna> Stavke_narudzbe_racuna { get; set; }
    }
}
