//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dodatni_podaci_korisnika
    {
        public int ID_korisnik { get; set; }
        public int ID_status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> OIB { get; set; }
        public Nullable<int> Bodovi { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
