//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dodatni_podaci_konzumenta
    {
        public int ID_korisnik { get; set; }
        public string Opis { get; set; }
        public string Slika { get; set; }
        public int ID_dodatni_podaci_konzumenta { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
