//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.Dodatni_podaci_konzumenta = new HashSet<Dodatni_podaci_konzumenta>();
            this.Dodatni_podaci_korisnika = new HashSet<Dodatni_podaci_korisnika>();
            this.Pracenje_po_datumima = new HashSet<Pracenje_po_datumima>();
            this.Pracenje_po_datumima1 = new HashSet<Pracenje_po_datumima>();
        }
    
        public int ID_korisnik { get; set; }
        public Nullable<bool> Konzument_korisnik { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Dodatni_podaci_konzumenta> Dodatni_podaci_konzumenta { get; set; }
        public virtual ICollection<Dodatni_podaci_korisnika> Dodatni_podaci_korisnika { get; set; }
        public virtual ICollection<Pracenje_po_datumima> Pracenje_po_datumima { get; set; }
        public virtual ICollection<Pracenje_po_datumima> Pracenje_po_datumima1 { get; set; }
    }
}
