//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mjerne_jedinice
    {
        public Mjerne_jedinice()
        {
            this.Artikli = new HashSet<Artikli>();
        }
    
        public int ID_mjerna_jedinica { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Artikli> Artikli { get; set; }
    }
}
