//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Status> Status { get; set; }
        public DbSet<Dodatni_podaci_korisnika> Dodatni_podaci_korisnika { get; set; }
        public DbSet<Dodatni_podaci_konzumenta> Dodatni_podaci_konzumenta { get; set; }
        public DbSet<Korisnici> Korisnici { get; set; }
        public DbSet<Pracenje_po_datumima> Pracenje_po_datumima { get; set; }
    }
}
