//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe_racuni
    {
        public Narudzbe_racuni()
        {
            this.Stavke_narudzbe_racuna = new HashSet<Stavke_narudzbe_racuna>();
        }
    
        public int ID_narudzba_racun { get; set; }
        public Nullable<int> ID_korisnik { get; set; }
        public Nullable<int> ID_konzument { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<double> Iznos { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Korisnici Korisnici1 { get; set; }
        public virtual ICollection<Stavke_narudzbe_racuna> Stavke_narudzbe_racuna { get; set; }
    }
}
