//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracenje_po_datumima
    {
        public int ID_pracenje_po_datumu { get; set; }
        public Nullable<int> ID_korisnik { get; set; }
        public Nullable<int> ID_konzument { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Visina { get; set; }
        public Nullable<double> Tezina { get; set; }
        public string Mjere { get; set; }
        public string Komentar { get; set; }
        public string Biljeske { get; set; }
        public string Slika { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Korisnici Korisnici1 { get; set; }
    }
}
