//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3MIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_narudzbe_racuna
    {
        public int ID_narudzba_racun { get; set; }
        public int ID_artikal { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<double> Cijena { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        public virtual Narudzbe_racuni Narudzbe_racuni { get; set; }
    }
}
